CREATE TABLE EMPLOYEE (
    ID              INT PRIMARY KEY,
    EMPLOYEE_ID     INT NOT NULL UNIQUE,
    EMPLOYEE_NAME   varchar(50) NOT NULL,
    DEPT_NAME       varchar(50) NOT NULL,
    JOINING_DATE    DATE NOT NULL,
    EMP_LWD         DATE,
    CREATED_USERID  INT NOT NULL,
    CREATED_DATE    DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_USERID  INT,
    UPDATED_DATE    DATETIME,
    CONSTRAINT chk_emp_lwd CHECK (EMP_LWD IS NULL OR EMP_LWD >= JOINING_DATE)
);

CREATE TABLE USER_CREDENTIALS (
    ID               INT PRIMARY KEY,  
    EMAIL_ID         varchar(50) NOT NULL UNIQUE,
    PASSWORD         varchar(50) NOT NULL,
    IS_ADMIN_Y_N     CHAR(1) NOT NULL,
    CREATED_USERID   INT NOT NULL,
    CREATED_DATE     DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_USERID   INT,
    CONSTRAINT chk_is_admin CHECK (IS_ADMIN_Y_N IN ('Y', 'N')),
    CONSTRAINT fk_user_id FOREIGN KEY (ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT fk_created_user FOREIGN KEY (CREATED_USERID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT fk_updated_user FOREIGN KEY (UPDATED_USERID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

insert into USER_CREDENTIALS(ID,EMAIL_ID)


CREATE TABLE EMP_TIMESHEET (
    ID              INT PRIMARY KEY,
    TS_DATE          DATE NOT NULL,
    WORKED_HOURS     NUMBER(4,2),
    START_TIME       TIMESTAMP NOT NULL,
    END_TIME         TIMESTAMP NOT NULL,
    IS_VACATION_Y_N  CHAR(1) NOT NULL,
    CREATED_USERID   INT NOT NULL REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CREATED_DATE     DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_USERID   INT REFERENCES EMPLOYEE(EMPLOYEE_ID),
    UPDATED_DATE     DATE,
    CONSTRAINT chk_time_order CHECK (END_TIME >= START_TIME),
    CONSTRAINT chk_is_vacation CHECK (IS_VACATION_Y_N IN ('Y', 'N'))
);


CREATE TABLE EMP_WEEKLY_OFF (
    ID      INT PRIMARY KEY,
    EMP_ID  INT REFERENCES EMPLOYEE(EMPLOYEE_ID),
    DAY     varchar(10) NOT NULL, 
    CONSTRAINT chk_valid_day CHECK (UPPER(DAY) IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'))
);


CREATE TABLE ORG_HOLIDAYS (
    ID              INT PRIMARY KEY,
    FINANCIAL_YEAR  NUMBER(4) NOT NULL,
    HOLIDAY_DATE    DATE NOT NULL,
    OCCASION        varchar(50) NOT NULL,
    CONSTRAINT uq_finyear_date UNIQUE (FINANCIAL_YEAR, HOLIDAY_DATE)
);
