CREATE TABLE EMPLOYEE (
    ID              INT PRIMARY KEY,
    EMPLOYEE_ID     INT NOT NULL UNIQUE,
    EMPLOYEE_NAME   varchar(50) NOT NULL,
    DEPT_NAME       varchar(50) NOT NULL,
    JOINING_DATE    DATE NOT NULL,
    EMP_LWD         DATE,
    CREATED_USERID  INT NOT NULL,
    CREATED_DATE    DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_USERID  INT,
    UPDATED_DATE    DATETIME,
    CONSTRAINT chk_emp_lwd CHECK (EMP_LWD IS NULL OR EMP_LWD >= JOINING_DATE)
);
insert into employee(EMPLOYEE_ID,EMPLOYEE_NAME,DEPT_NAME,JOINING_DATE,EMP_LWD,CREATED_USERID,CREATED_DATE,UPDATED_USERID,UPDATED_DATE) values(1,'Charanjith','IT','2025-10-19',NULL,1,CURRENT_TIMESTAMP,null,null);

ALTER TABLE EMPLOYEE MODIFY ID INT NOT NULL AUTO_INCREMENT ;

CREATE TABLE USER_CREDENTIALS (
    ID               INT PRIMARY KEY AUTO_INCREMENT,  
    EMAIL_ID         varchar(50) NOT NULL UNIQUE,
    PASSWORD         varchar(50) NOT NULL,
    IS_ADMIN_Y_N     CHAR(1) NOT NULL,
    CREATED_USERID   INT NOT NULL,
    CREATED_DATE     DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_USERID   INT,
    CONSTRAINT chk_is_admin CHECK (IS_ADMIN_Y_N IN ('Y', 'N')),
    CONSTRAINT fk_user_id FOREIGN KEY (ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT fk_created_user FOREIGN KEY (CREATED_USERID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT fk_updated_user FOREIGN KEY (UPDATED_USERID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

insert into USER_CREDENTIALS(EMAIL_ID,PASSWORD,IS_ADMIN_Y_N,CREATED_USERID,UPDATED_USERID) values('charanjith.angadi@gmail.com','1234','Y',1,null);


CREATE TABLE EMP_TIMESHEET (
    ID              INT PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_ID     INT,
    TS_DATE          DATE NOT NULL,
    WORKED_HOURS     DECIMAL(4,2),
    IS_VACATION_Y_N  CHAR(1) NOT NULL,
    CREATED_USERID   INT NOT NULL REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CREATED_DATE     DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_USERID   INT REFERENCES EMPLOYEE(EMPLOYEE_ID),
    UPDATED_DATE     DATE,
    CONSTRAINT fk_user_id_EMP_TS FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT chk_is_vacation CHECK (IS_VACATION_Y_N IN ('Y', 'N'))
);